# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'vs2017-win2016'

name: $(Date:yyyyMMdd)$(rev:.rr)

variables:
  registry: '$(AcrId).azurecr.io'
  imageName: 'tfnuget.server:$(Build.BuildNumber)'

steps:
- script: docker login --username $(AcrId) --password $(Password) $(registry)
  displayName: 'docker login'

- script: docker build --file .\docker\publish\Dockerfile --tag nugetserver-publish .
  displayName: 'docker build publish image'

- script: docker container create --name nugetserver-publish-1 nugetserver-publish
  displayName: 'docker create publish container'

- script: docker container cp nugetserver-publish-1:C:\\build\\out\\web\\ThinkFinanceNuGet.Server\\_PublishedWebsites .\\ThinkFinanceNuGet.Server\\_PublishedWebsites
  displayName: 'docker copy website files'

- script: docker container rm nugetserver-publish-1
  displayName: 'docker rm temp nugetserver-publish-1 container'

- script: docker image rm nugetserver-publish
  displayName: 'docker rm publish image'

- script: docker build --file .\docker\web\Dockerfile --tag $(registry)/$(imageName) .
  displayName: 'docker build image'

- script: docker push $(AcrId).azurecr.io/$(imageName)
  displayName: 'docker push image'
